=== zhou0bin/zhou0bin/remote_cod/diag_script_parser/GenerateOtx/DiagnosticProcedureV6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (http://www.altova.com) by  () -->
<!--W3C Schema generated by XMLSpy v2013 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Procedure" type="Procedure"/>
	<xs:complexType name="Step">
		<xs:all>
			<xs:element name="Conditions" type="Conditions"/>
			<xs:element name="BaseVariables" type="BaseVariables" minOccurs="0"/>
			<xs:element name="Assement" type="Assement"/>
			<xs:element name="Steps" type="Steps" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="Title" use="required"/>
		<xs:attribute name="IsActive" type="xs:boolean" use="required"/>
		<xs:attribute name="StepType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:short"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="FunctionName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="100"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="GUID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Stp_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Steps">
		<xs:sequence>
			<xs:element name="Step" type="Step" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Condition" abstract="true">
		<xs:attribute name="Type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Programtic"/>
					<xs:enumeration value="LAS"/>
					<xs:enumeration value="PreviousResult"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="IsActive" type="xs:boolean" default="false"/>
	</xs:complexType>
	<xs:complexType name="Procedure">
		<xs:sequence>
			<xs:element name="StatBlock" type="StatBlock"/>
			<xs:element name="EditHistoryList" type="EditHistoryList"/>
			<xs:element name="LocalVariables" type="LocalVariables"/>
			<xs:element name="Steps" type="Steps"/>
		</xs:sequence>
		<xs:attribute name="Title" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="GUID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Proc_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Creator" use="required"/>
	</xs:complexType>
	<xs:complexType name="LocalVariable">
		<xs:attribute name="BaseDataType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="bool"/>
					<xs:enumeration value="int"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="float"/>
					<xs:enumeration value="double"/>
					<xs:enumeration value="object"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="VariableName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Value" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="GUID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="BsVar_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="VariableType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="vciResult"/>
					<xs:enumeration value="bool"/>
					<xs:enumeration value="ecuDtObj"/>
					<xs:enumeration value="int"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="float"/>
					<xs:enumeration value="double"/>
					<xs:enumeration value="LAS"/>
					<xs:enumeration value="JsonObj"/>
					<xs:enumeration value="StatStep"/>
					<xs:enumeration value="object"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="DefaultValue" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="LocalVariables">
		<xs:sequence>
			<xs:element name="LocalVariable" type="LocalVariable" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Conditions">
		<xs:sequence>
			<xs:element name="Condition" type="Condition" minOccurs="3" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LAS">
		<xs:complexContent>
			<xs:extension base="LocalVariable">
				<xs:attribute name="LASExpression" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="BaseVariable">
		<xs:attribute name="VariableType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="int"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="bool"/>
					<xs:enumeration value="double"/>
					<xs:enumeration value="float"/>
					<xs:enumeration value="object"/>
					<xs:enumeration value="ecuDtObj"/>
					<xs:enumeration value="vciResult"/>
					<xs:enumeration value="StatStep"/>
					<xs:enumeration value="LAS"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="VariableName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Value" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="IsOptional" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="InOutType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:byte">
					<xs:enumeration value="0"/>
					<xs:enumeration value="1"/>
					<xs:enumeration value="2"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="GUID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="BsVar_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="DefaultValue" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="BindLocalVarGUID" type="xs:string" use="required"/>
		<xs:attribute name="IsByBinding" type="xs:boolean" default="false"/>
		<xs:attribute name="BaseDataType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="bool"/>
					<xs:enumeration value="int"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="double"/>
					<xs:enumeration value="object"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="BaseVariables">
		<xs:sequence>
			<xs:element name="BaseVariable" type="BaseVariable" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Expression">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="Value" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="LASRef">
		<xs:attribute name="LasId" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:IDREF">
					<xs:pattern value="BsVar_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="LASCondition">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:sequence>
					<xs:element name="LASRef" type="LASRef"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ProgramticCondition">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:sequence>
					<xs:element name="Expression" type="Expression"/>
				</xs:sequence>
				<xs:attribute name="ExcuteAt" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Always"/>
							<xs:enumeration value="If"/>
							<xs:enumeration value="While"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="EditHistory">
		<xs:attribute name="Editor" type="xs:string" use="required"/>
		<xs:attribute name="EditTime" type="xs:dateTime" use="required"/>
		<xs:attribute name="EditContent" type="xs:string" use="required"/>
		<xs:attribute name="Version" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="V[0-9]{1,4}.[0-9]{1,4}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="EditHistoryList">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="EditHistory" type="EditHistory"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ecuDtObj">
		<xs:complexContent>
			<xs:extension base="LocalVariable">
				<xs:attribute name="Name" type="xs:string" use="required"/>
				<xs:attribute name="RequestID" type="xs:unsignedShort" use="required"/>
				<xs:attribute name="ResponseID" type="xs:unsignedShort" use="required"/>
				<xs:attribute name="FrameType" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:unsignedInt">
							<xs:enumeration value="0"/>
							<xs:enumeration value="1"/>
							<xs:enumeration value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="StatStep">
		<xs:complexContent>
			<xs:extension base="LocalVariable">
				<xs:attribute name="ID" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:unsignedLong">
							<xs:pattern value="[0-9]{1,9}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="EnglishTitle" type="xs:string" use="required"/>
				<xs:attribute name="ChineseTitle" type="xs:string" use="required"/>
				<xs:attribute name="PrintAtNOK" type="xs:boolean" use="required"/>
				<xs:attribute name="PrintAtOK" type="xs:boolean" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="StatBlock">
		<xs:attribute name="ID" type="xs:long" use="required"/>
		<xs:attribute name="GUID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="StatBlk_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="EnglishTitle" type="xs:string" use="required"/>
		<xs:attribute name="ChineseTitle" type="xs:string" use="required"/>
		<xs:attribute name="PrintAtNOK" type="xs:boolean" use="required"/>
		<xs:attribute name="PrintAtOK" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="PreviousResultCondition">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:attribute name="PreviousResult" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="OK"/>
							<xs:enumeration value="NOK"/>
							<xs:enumeration value="ABORT"/>
							<xs:enumeration value="NONE"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="ExcuteAt" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Always"/>
							<xs:enumeration value="If"/>
							<xs:enumeration value="While"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Assement">
		<xs:attribute name="IsActive" type="xs:boolean" use="required"/>
		<xs:attribute name="Action" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="None"/>
					<xs:enumeration value="Cancel"/>
					<xs:enumeration value="Repeat"/>
					<xs:enumeration value="Terminate"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="IsAssmentAtOKEnable" type="xs:boolean" use="required"/>
		<xs:attribute name="IsAssmentAtNOKEnable" type="xs:boolean" use="required"/>
		<xs:attribute name="IsAssmentAtAbortEnable" type="xs:boolean" use="required"/>
		<xs:attribute name="IsAssmentAtProgramaticEnable" type="xs:boolean" use="required"/>
		<xs:attribute name="ProgramaticAssement" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== zhou0bin/zhou0bin/remote_cod/diag_script_parser/GenerateOtx/new_xml_2021_03_30/testCCU.xml
<Procedure Title="" GUID="Proc_3aafdbcec01c405f9cfa99c578a25afb" Creator="GAC" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/%e5%ad%a6%e4%b9%a0%e8%b5%84%e6%96%99/%e6%80%bb%e7%ba%bf%e8%af%8a%e6%96%ad%e5%ad%a6%e4%b9%a0%e8%b5%84%e6%96%99/1%e8%bd%a6%e5%9e%8b%e9%a1%b9%e7%9b%ae/A02/%e8%84%9a%e6%9c%ac%e6%a0%b7%e4%be%8b/%e5%b9%bf%e6%b1%bd%e8%84%9a%e6%9c%ac/DiagnosticProcedureV6.xsd">
	<StatBlock ID="1" GUID="StatBlk_a9cf31f591b94bf0a9221f655b954d3a" EnglishTitle="Test Block" ChineseTitle="测试序列" PrintAtNOK="true" PrintAtOK="true"/>
	<EditHistoryList/>
	<LocalVariables>
		<LocalVariable VariableName="StatStep_Write0100" GUID="BsVar_49581357fe944c1594a823ee64913304" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="24" EnglishTitle="Write 0100" ChineseTitle="写入0100" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="IsIDOK" GUID="BsVar_e731951bea664696a23bb77c6a198315" Value="false" VariableType="bool" BaseDataType="bool" DefaultValue=""/>
		<LocalVariable VariableName="dict1" GUID="BsVar_559c0f7bde8f49aa981a1b651201749c" Value="{'DTC':'14A311','DTCExtendedDataRecordNumber':'ff'}" VariableType="object" BaseDataType="object" DefaultValue=""/>
		<LocalVariable VariableName="StatStepClearDTC" GUID="BsVar_ce36e097aebe449b80da36826b8b51aa" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="43" EnglishTitle="Clear DTC" ChineseTitle="清除故障码" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="Int3" GUID="BsVar_96ee796f07ef4114b0f0a68e0c77c337" Value="3" VariableType="int" BaseDataType="int" DefaultValue=""/>
		<LocalVariable VariableName="Time100" GUID="BsVar_d3c45d27772d404cb84c784ceae99c25" Value="100" VariableType="int" BaseDataType="int" DefaultValue=""/>
		<LocalVariable VariableName="ResultHWID" GUID="BsVar_5a2a97b00af1480682e58ffecba5b155" Value="" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="StatStepRead0204" GUID="BsVar_59a2a0c41e984624b257a5092713ca18" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="41" EnglishTitle="read 0204" ChineseTitle="读取0204" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="ResultID" GUID="BsVar_fe82bec3b7864feb826f3738f14d1a3d" Value="" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="StatStepCheckVIN" GUID="BsVar_673485934e374a4abebeb26b09a20183" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="40" EnglishTitle="Check VIN" ChineseTitle="检查VIN" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="RequestStr" GUID="BsVar_7118a16aebf54ed4a280f5b3e41765f5" Value="220204" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="IsWriteSuccessful" GUID="BsVar_bea78f15da52486380f1dc5ac5546f6b" Value="false" VariableType="bool" BaseDataType="bool" DefaultValue=""/>
		<LocalVariable VariableName="StatStepWriteVIN" GUID="BsVar_0928b0aed08648c58992f6088d2df64a" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="38" EnglishTitle="Write VIN" ChineseTitle="写入VIN" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="StatStep_StartCom" GUID="BsVar_81d58e7888974a2a9f2c97ca47ee2eb0" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="3" EnglishTitle="Start Com Failed" ChineseTitle="启动通讯失败" PrintAtNOK="false" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="StatStepCheck0110" GUID="BsVar_65fc5e025edf4ece81e6fdaf56c793e1" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="37" EnglishTitle="Check 0110" ChineseTitle="检查0110" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="dict2" GUID="BsVar_17591b7b59b640ef8bcf942a680e4af5" Value="{'DTC':'14A311','DTCSnapshotRecordNumber':'ff'}" VariableType="object" BaseDataType="object" DefaultValue=""/>
		<LocalVariable VariableName="IsReadSuccessful" GUID="BsVar_4cedbbbeafee469ba9d26602dcf55414" Value="false" VariableType="bool" BaseDataType="bool" DefaultValue=""/>
		<LocalVariable VariableName="ResultSWID" GUID="BsVar_2814d1cd05d9469c8373750cf280bc7e" Value="" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="StatStep_CheckID" GUID="BsVar_14961346f0774738a68015a6f4df6812" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="18" EnglishTitle="Check ECU ID" ChineseTitle="检查零件号" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="StatStepGAC_SparePartNumberDataIdentifier_F187_Read" GUID="BsVar_6499674ca9394315936a63e62bb1ba2f" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="47" EnglishTitle="Read ID" ChineseTitle="读取零件号" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="Str_0100" GUID="BsVar_329b3493f50d4acda8ae2581bf368dfa" Value="0100" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="Result" GUID="BsVar_532aa135acfd42e692c061492b3b4d05" Value="false" VariableType="bool" BaseDataType="bool" DefaultValue=""/>
		<LocalVariable VariableName="StatStepRead_DTC_Extended_data" GUID="BsVar_92eda761c1ad492eac8d52b31ebdb4d8" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="50" EnglishTitle="Read Extended Data" ChineseTitle="读取拓展数据" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="NoneObject" GUID="BsVar_76d9c513371746e69cc3d11b21f8da2e" Value="None" VariableType="object" BaseDataType="object" DefaultValue=""/>
		<LocalVariable VariableName="ShortNameGAC_ECUSoftwareVersionNumber_F189_Read" GUID="BsVar_d15c1830e43a4ba99623add2d560fcc7" Value="GAC_ECUSoftwareVersionNumber_F189_Read" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="StatStep_CheckHWID" GUID="BsVar_c8333e1057d54b8d98c52367ef848b53" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="20" EnglishTitle="Check ECU HWID" ChineseTitle="检查ECU硬件版本号" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="StatStepGAC_ECUHardwareVersionNumber_F17F_Read" GUID="BsVar_4bb7aa158132496483a4b9bf51cebcda" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="49" EnglishTitle="Read HW number" ChineseTitle="读取硬件版本号" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="ShortNameGAC_SparePartNumberDataIdentifier_F187_Read" GUID="BsVar_66259dd5ccdf48b4a28352e63272a740" Value="GAC_SparePartNumberDataIdentifier_F187_Read" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="StatStepCheck0204" GUID="BsVar_5249bfee5eba4445815f857d30fa4fe4" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="42" EnglishTitle="check 0204" ChineseTitle="检查0204" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="IsExcuteSuccessful" GUID="BsVar_b19fd4a221d54c10aa717ed22e1b8538" Value="false" VariableType="bool" BaseDataType="bool" DefaultValue=""/>
		<LocalVariable VariableName="IsSWIDOK" GUID="BsVar_e10fabca665a482980e6d59bcf599811" Value="false" VariableType="bool" BaseDataType="bool" DefaultValue=""/>
		<LocalVariable VariableName="StatStepExtendedDiagnostic_Control" GUID="BsVar_26a2c9d61cdb45b58d33e6d34603fa7d" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="46" EnglishTitle="Enter Extended Diagnostic Control" ChineseTitle="进入拓展模式" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
		<LocalVariable VariableName="VciResultSWID" GUID="BsVar_10f909a495474c249dd7d654702d644d" Value="" VariableType="vciResult" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="IsSuccess" GUID="BsVar_0199c96c2e124d30802f9de57950f1e1" Value="false" VariableType="bool" BaseDataType="bool" DefaultValue=""/>
		<LocalVariable VariableName="Str_00000000" GUID="BsVar_acefc61d59154ecc988ec6b1bd9730a2" Value="00000000" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="ShortNameFault_Memory_Read_Snapshot_record_by_DTC_number" GUID="BsVar_c8f50e0259074d5e9ae55aaef1dfbf14" Value="Fault_Memory_Read_Snapshot_record_by_DTC_number" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="ShortNameGAC_ECUHardwareVersionNumber_F17F_Read" GUID="BsVar_80d57684186a4e2f9f0d8897e6fb8002" Value="GAC_ECUHardwareVersionNumber_F17F_Read" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="VciResultWrite" GUID="BsVar_3f5a206b1b7147a3ac735a134bd6afcd" Value="" VariableType="vciResult" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="VciResultRead" GUID="BsVar_b224894977014621acc5fe2eaa2743e8" Value="" VariableType="vciResult" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="Str_OdxNegtiveResponse" GUID="BsVar_e2af07c9e61e4c5d8450223ce0fe60ba" Value="" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="Str_empty" GUID="BsVar_3683fffe06ad429c83200f3b1de4845a" Value="" VariableType="string" BaseDataType="string" DefaultValue=""/>
		<LocalVariable VariableName="StatStep_CheckSWID" GUID="BsVar_da8c5d5f83d84866bb1bf8a7ebd0d209" Value="" VariableType="StatStep" BaseDataType="object" DefaultValue="" ID="19" EnglishTitle="Check ECU SWID" ChineseTitle="检查ECU 软件版本号" PrintAtNOK="true" PrintAtOK="false" xsi:type="StatStep"/>
