=== zhou0bin/zhou0bin/remote_cod/diag_script_parser/GenerateOtx/DiagnosticProcedureV5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (http://www.altova.com) by  () -->
<!--W3C Schema generated by XMLSpy v2013 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Procedure" type="Procedure"/>
	<xs:complexType name="Step">
		<xs:all>
			<xs:element name="Conditions" type="Conditions"/>
			<xs:element name="BaseVariables" type="BaseVariables" minOccurs="0"/>
			<xs:element name="Assement" type="Assement"/>
			<xs:element name="Steps" type="Steps" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="Title" use="required"/>
		<xs:attribute name="isActive" type="xs:boolean" use="required"/>
		<xs:attribute name="StepType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:short">
					<xs:enumeration value="0"/>
					<xs:enumeration value="1"/>
					<xs:enumeration value="2"/>
					<xs:enumeration value="100"/>
					<xs:enumeration value="101"/>
					<xs:enumeration value="102"/>
					<xs:enumeration value="103"/>
					<xs:enumeration value="104"/>
					<xs:enumeration value="105"/>
					<xs:enumeration value="106"/>
					<xs:enumeration value="107"/>
					<xs:enumeration value="108"/>
					<xs:enumeration value="109"/>
					<xs:enumeration value="110"/>
					<xs:enumeration value="111"/>
					<xs:enumeration value="112"/>
					<xs:enumeration value="113"/>
					<xs:enumeration value="114"/>
					<xs:enumeration value="115"/>
					<xs:enumeration value="116"/>
					<xs:enumeration value="117"/>
					<xs:enumeration value="118"/>
					<xs:enumeration value="119"/>
					<xs:enumeration value="120"/>
					<xs:enumeration value="121"/>
					<xs:enumeration value="122"/>
					<xs:enumeration value="123"/>
					<xs:enumeration value="124"/>
					<xs:enumeration value="125"/>
					<xs:enumeration value="126"/>
					<xs:enumeration value="127"/>
					<xs:enumeration value="1000"/>
					<xs:enumeration value="1001"/>
					<xs:enumeration value="1002"/>
					<xs:enumeration value="1003"/>
					<xs:enumeration value="5000"/>
					<xs:enumeration value="9001"/>
					<xs:enumeration value="9002"/>
					<xs:enumeration value="9003"/>
					<xs:enumeration value="9004"/>
					<xs:enumeration value="9005"/>
					<xs:enumeration value="9006"/>
					<xs:enumeration value="9007"/>
					<xs:enumeration value="9008"/>
					<xs:enumeration value="9009"/>
					<xs:enumeration value="9010"/>
					<xs:enumeration value="9011"/>
					<xs:enumeration value="9012"/>
					<xs:enumeration value="9013"/>
					<xs:enumeration value="9014"/>
					<xs:enumeration value="9015"/>
					<xs:enumeration value="9016"/>
					<xs:enumeration value="9017"/>
					<xs:enumeration value="5001"/>
					<xs:enumeration value="5002"/>
					<xs:enumeration value="5003"/>
					<xs:enumeration value="5004"/>
					<xs:enumeration value="5005"/>
					<xs:enumeration value="5006"/>
					<xs:enumeration value="5007"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="StepName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="100"/>
					<xs:enumeration value="Transmit"/>
					<xs:enumeration value="SetValue"/>
					<xs:enumeration value="WaitFor"/>
					<xs:enumeration value="StartCom"/>
					<xs:enumeration value="DefaultSession"/>
					<xs:enumeration value="ReadDTC"/>
					<xs:enumeration value="ClearDTC"/>
					<xs:enumeration value="HWReset"/>
					<xs:enumeration value="SWReset"/>
					<xs:enumeration value="CheckFactoryMode"/>
					<xs:enumeration value="WriteAndCheckConfig"/>
					<xs:enumeration value="CheckConfig"/>
					<xs:enumeration value="WriteAndCheckMTOC"/>
					<xs:enumeration value="CheckMTOC"/>
					<xs:enumeration value="WriteAndCheckVIN"/>
					<xs:enumeration value="CheckVIN"/>
					<xs:enumeration value="AssemblyCheck"/>
					<xs:enumeration value="ReadAndUploadInServer"/>
					<xs:enumeration value="ReadByteAndCheckValue"/>
					<xs:enumeration value="ReadByteAndCheckRange"/>
					<xs:enumeration value="ReadBitAndCheckValue"/>
					<xs:enumeration value="ReadCompareID"/>
					<xs:enumeration value="PeriodicallyReadByteAndCheckValue"/>
					<xs:enumeration value="PeriodicallyReadByteAndCheckRange"/>
					<xs:enumeration value="PeriodicallyReadBitAndCheckValue"/>
					<xs:enumeration value="ExcuteServiceAndCheckResponse"/>
					<xs:enumeration value="PeriodicallyExcuteServiceAndCheckResponse"/>
					<xs:enumeration value="ReadDIDAndWrite"/>
					<xs:enumeration value="QuitAndCheckFactoryMode"/>
					<xs:enumeration value="GeneratePinFromVIN"/>
					<xs:enumeration value="EvaluateLas"/>
					<xs:enumeration value="GetSection"/>
					<xs:enumeration value="GenerateESK"/>
					<xs:enumeration value="Blank"/>
					<xs:enumeration value="CallProcedure"/>
					<xs:enumeration value="CallOdxServiceByShortName"/>
					<xs:enumeration value="CallOdxServiceByShortName"/>
					<xs:enumeration value="StringCat"/>
					<xs:enumeration value="StringCut"/>
					<xs:enumeration value="StringTrim"/>
					<xs:enumeration value="StringToUpper"/>
					<xs:enumeration value="StringToLower"/>
					<xs:enumeration value="StringToInt"/>
					<xs:enumeration value="StringToByteField"/>
					<xs:enumeration value="ByteFieldToString"/>
					<xs:enumeration value="ByteFieldCat"/>
					<xs:enumeration value="IntAdd"/>
					<xs:enumeration value="IntSubtract"/>
					<xs:enumeration value="IntMultiply"/>
					<xs:enumeration value="IntDivide"/>
					<xs:enumeration value="FloatAdd"/>
					<xs:enumeration value="FloatSubtract"/>
					<xs:enumeration value="FloatMultiply"/>
					<xs:enumeration value="FloatDivide"/>
					<xs:enumeration value="MessageBox"/>
					<xs:enumeration value="InputBox"/>
					<xs:enumeration value="SelectionList"/>
					<xs:enumeration value="GetVin"/>
					<xs:enumeration value="GetMtoc"/>
					<xs:enumeration value="GetFeatureCodes"/>
					<xs:enumeration value="SecurityAccess"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="GUID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Stp_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Steps">
		<xs:sequence>
			<xs:element name="Step" type="Step" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Condition" abstract="true">
		<xs:attribute name="Type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Programtic"/>
					<xs:enumeration value="LAS"/>
					<xs:enumeration value="PreviousResult"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="IsActive" type="xs:boolean" default="false"/>
	</xs:complexType>
	<xs:complexType name="Procedure">
		<xs:sequence>
			<xs:element name="StatBlock" type="StatBlock"/>
			<xs:element name="EditHistoryList" type="EditHistoryList"/>
			<xs:element name="LocalVariables" type="LocalVariables"/>
			<xs:element name="Steps" type="Steps"/>
		</xs:sequence>
		<xs:attribute name="Title" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="GUID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Proc_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Creator" use="required"/>
	</xs:complexType>
	<xs:complexType name="LocalVariable">
		<xs:attribute name="BaseDataType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="bool"/>
					<xs:enumeration value="int"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="float"/>
					<xs:enumeration value="double"/>
					<xs:enumeration value="object"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="VariableName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Value" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="GUID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="BsVar_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="VariableType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="vciResult"/>
					<xs:enumeration value="bool"/>
					<xs:enumeration value="ecuDtObj"/>
					<xs:enumeration value="int"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="float"/>
					<xs:enumeration value="VciResult"/>
					<xs:enumeration value="double"/>
					<xs:enumeration value="LAS"/>
					<xs:enumeration value="JsonObj"/>
					<xs:enumeration value="StatStep"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="DefaultValue" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="LocalVariables">
		<xs:sequence>
			<xs:element name="LocalVariable" type="LocalVariable" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Conditions">
		<xs:sequence>
			<xs:element name="Condition" type="Condition" minOccurs="3" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LAS">
		<xs:complexContent>
			<xs:extension base="LocalVariable">
				<xs:attribute name="LASExpression" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="BaseVariable">
		<xs:attribute name="VariableType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="bool"/>
					<xs:enumeration value="int"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="ecuDtObj"/>
					<xs:enumeration value="vciResult"/>
					<xs:enumeration value="StatStep"/>
					<xs:enumeration value="Dict"/>
					<xs:enumeration value="las"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="VariableName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Value" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="IsOptional" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="InOutType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:byte">
					<xs:enumeration value="0"/>
					<xs:enumeration value="1"/>
					<xs:enumeration value="2"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="GUID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="BsVar_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="DefaultValue" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="BindLocalVarGUID" type="xs:string" use="required"/>
		<xs:attribute name="IsByBinding" type="xs:boolean" default="false"/>
		<xs:attribute name="BaseDataType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="bool"/>
					<xs:enumeration value="int"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="double"/>
					<xs:enumeration value="object"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="BaseVariables">
		<xs:sequence>
			<xs:element name="BaseVariable" type="BaseVariable" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Expression">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="Value" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="LASRef">
		<xs:attribute name="LasId" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:IDREF">
					<xs:pattern value="BsVar_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="LASCondition">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:sequence>
					<xs:element name="LASRef" type="LASRef"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ProgramticCondition">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:sequence>
					<xs:element name="Expression" type="Expression"/>
				</xs:sequence>
				<xs:attribute name="ExcuteAt" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Always"/>
							<xs:enumeration value="If"/>
							<xs:enumeration value="While"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="EditHistory">
		<xs:attribute name="Editor" type="xs:string" use="required"/>
		<xs:attribute name="EditTime" type="xs:dateTime" use="required"/>
		<xs:attribute name="EditContent" type="xs:string" use="required"/>
		<xs:attribute name="VersionNum" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="V[0-9]{1,4}.[0-9]{1,4}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="EditHistoryList">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="EditHistory" type="EditHistory"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ecuDtObj">
		<xs:complexContent>
			<xs:extension base="LocalVariable">
				<xs:attribute name="Name" type="xs:string" use="required"/>
				<xs:attribute name="RequestID" type="xs:unsignedShort" use="required"/>
				<xs:attribute name="ResponseID" type="xs:unsignedShort" use="required"/>
				<xs:attribute name="FrameType" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:unsignedInt">
							<xs:enumeration value="0"/>
							<xs:enumeration value="1"/>
							<xs:enumeration value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="StatStep">
		<xs:complexContent>
			<xs:extension base="LocalVariable">
				<xs:attribute name="ID" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:unsignedLong">
							<xs:pattern value="[0-9]{1,9}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="EnglishTranslation" type="xs:string" use="required"/>
				<xs:attribute name="ChineseTranslation" type="xs:string" use="required"/>
				<xs:attribute name="PrintAtNok" type="xs:boolean" use="required"/>
				<xs:attribute name="PrintAtOK" type="xs:boolean" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="StatBlock">
		<xs:attribute name="ID" type="xs:long" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="GUID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="StatBlk_[a-f0-9]{32}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="EnglishTranslation" type="xs:string" use="required"/>
		<xs:attribute name="ChineseTranslation" type="xs:string" use="required"/>
		<xs:attribute name="PrintAtNok" type="xs:boolean" use="required"/>
		<xs:attribute name="PrintAtOK" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="PreviousResultCondition">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:attribute name="PreviousResult" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="OK"/>
							<xs:enumeration value="NOK"/>
							<xs:enumeration value="ABORT"/>
							<xs:enumeration value="NONE"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="ExcuteAt" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Always"/>
							<xs:enumeration value="If"/>
							<xs:enumeration value="While"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Assement">
		<xs:attribute name="IsActive" type="xs:boolean" use="required"/>
		<xs:attribute name="Action" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="None"/>
					<xs:enumeration value="Cancel"/>
					<xs:enumeration value="Repeat"/>
					<xs:enumeration value="Terminate"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="IsAssmentAtOKEnable" type="xs:boolean" use="required"/>
		<xs:attribute name="IsAssmentAtNOKEnable" type="xs:boolean" use="required"/>
		<xs:attribute name="IsAssmentAtAbortEnable" type="xs:boolean" use="required"/>
		<xs:attribute name="IsAssmentAtProgramaticEnable" type="xs:boolean" use="required"/>
		<xs:attribute name="ProgramaticAssement" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== zhou0bin/zhou0bin/remote_cod/diag_script_parser/GenerateOtx/new_xml_2022_02_14/SRS_Init.xml
<!-- edited with XMLSpy v2013 (http://www.altova.com) by  () -->
<Procedure Title="SRS_Init" Creator="GAC" GUID="Proc_cf5cdb0c6d5d4d92a6ae8b927a65747e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/%e5%ad%a6%e4%b9%a0%e8%b5%84%e6%96%99/%e6%80%bb%e7%ba%bf%e8%af%8a%e6%96%ad%e5%ad%a6%e4%b9%a0%e8%b5%84%e6%96%99/1%e8%bd%a6%e5%9e%8b%e9%a1%b9%e7%9b%ae/A02/%e8%84%9a%e6%9c%ac%e6%a0%b7%e4%be%8b/%e5%b9%bf%e6%b1%bd%e8%84%9a%e6%9c%ac/DiagnosticProcedureV5.xsd">
	<StatBlock ID="1" Name="SRS_Init" GUID="StatBlk_14560477220c42189d5a8ca3bf09400e" EnglishTranslation="SRS init " ChineseTranslation="SRS 初始化" PrintAtNok="true" PrintAtOK="true"/>
	<EditHistoryList>
		<EditHistory Editor="GAC" EditTime="2021-11-16T16:43:33" EditContent="creat dcument" VersionNum="V1.0"/>
	</EditHistoryList>
	<LocalVariables>
		<LocalVariable BaseDataType="object" VariableName="SRS_DtObj" Value="" GUID="BsVar_11320477220c42189d5a8ca3bf09400e" VariableType="ecuDtObj" DefaultValue="" xsi:type="ecuDtObj" RequestID="1808" ResponseID="1936" Name="A18M_SRS" FrameType="1"/>
		<LocalVariable BaseDataType="bool" VariableName="Srs_Active_status" Value="false" GUID="BsVar_3359c277220c42189d5a8ca3bf09400e" VariableType="bool" DefaultValue="false"/>
		<LocalVariable BaseDataType="object" VariableName="SRS" Value="" GUID="BsVar_1123c277220c42189d5a8ca3bf09400e" VariableType="LAS" DefaultValue="" xsi:type="LAS" LASExpression="$0SR7"/>
		<LocalVariable BaseDataType="string" VariableName="VciResult" Value="" GUID="BsVar_1123c277720c42189d5a8ca3bf09400e" VariableType="vciResult" DefaultValue=""/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_StartCom" Value="" GUID="BsVar_2343c277720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="1" ChineseTranslation="启动通讯失败" EnglishTranslation="Start com Failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_DefaultSession" Value="" GUID="BsVar_2343c273720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="2" ChineseTranslation="返回默认模式失败" EnglishTranslation="default session Failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_FactoryModeRead" Value="" GUID="BsVar_2356c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="3" ChineseTranslation="工厂模式读取失败" EnglishTranslation="Factory Mode read Failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_FactoryModeCheck" Value="" GUID="BsVar_2343c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="4" ChineseTranslation="工厂模式检测失败" EnglishTranslation="Factory Mode check Failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_WriteVIN" Value="" GUID="BsVar_1593c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="5" ChineseTranslation="写入VIN失败" EnglishTranslation="write vin Failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_ReadVIN" Value="" GUID="BsVar_1752c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="6" ChineseTranslation="读取VIN失败" EnglishTranslation="read vin Failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_CheckVIN" Value="" GUID="BsVar_2391c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="7" ChineseTranslation="检查VIN失败" EnglishTranslation="check vin Failed"/>
		<LocalVariable BaseDataType="string" VariableName="StatStep_WriteMTOC" Value="" GUID="BsVar_1921c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="8" ChineseTranslation="写入MTOC失败" EnglishTranslation="write mtoc Failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_ReadMTOC" Value="" GUID="BsVar_3352c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="9" ChineseTranslation="读取MTOC失败" EnglishTranslation="read mtoc failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_CheckMTOC" Value="" GUID="BsVar_3583c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="10" ChineseTranslation="检查MTOC失败" EnglishTranslation="check mtoc  Failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_Writ0202" Value="" GUID="BsVar_2921c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="11" ChineseTranslation="写入0202失败" EnglishTranslation="write 0202 Failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_Read0202" Value="" GUID="BsVar_4352c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="12" ChineseTranslation="读取0202失败" EnglishTranslation="read 0202 failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_Check0202" Value="" GUID="BsVar_5583c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="13" ChineseTranslation="比对0202失败" EnglishTranslation="check 0202 Failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_Writ0204" Value="" GUID="BsVar_6921c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="14" ChineseTranslation="写入0204失败" EnglishTranslation="write 0204 Failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_Read0204" Value="" GUID="BsVar_7352c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="15" ChineseTranslation="读取0204失败" EnglishTranslation="read 0204 failed"/>
		<LocalVariable BaseDataType="object" VariableName="StatStep_Check0204" Value="" GUID="BsVar_8583c275720c42189d5a8ca3bf09400e" VariableType="StatStep" DefaultValue="" xsi:type="StatStep" PrintAtOK="false" PrintAtNok="true" ID="16" ChineseTranslation="清除0204失败失败" EnglishTranslation="check 0204 Failed"/>
	</LocalVariables>
	<Steps>
		<Step StepType="100" StepName="StartCom" Title="StartCom" GUID="Stp_f54b8cb17e5b457483a0a84658e5c0de" isActive="true">
			<Conditions>
				<Condition Type="LAS" xsi:type="LASCondition" IsActive="true">
					<LASRef LasId="BsVar_1123c277220c42189d5a8ca3bf09400e"/>
				</Condition>
				<Condition Type="Programtic" xsi:type="ProgramticCondition" IsActive="true" ExcuteAt="Always">
					<Expression Value="true"/>
				</Condition>
				<Condition Type="PreviousResult" PreviousResult="NONE" ExcuteAt="Always" xsi:type="PreviousResultCondition" IsActive="false"/>
			</Conditions>
			<BaseVariables>
				<BaseVariable VariableName="ECU" InOutType="0" Value="SRS_DtObj" VariableType="ecuDtObj" BaseDataType="object" DefaultValue="" GUID="BsVar_df6bc277220c42189d5a8ca3bf09400e" IsByBinding="true" IsOptional="false" BindLocalVarGUID="BsVar_11320477220c42189d5a8ca3bf09400e"/>
				<BaseVariable VariableName="StatStepExcute" InOutType="0" Value="StatStep_StartCom" IsOptional="true" VariableType="StatStep" BaseDataType="object" DefaultValue="" GUID="BsVar_f79bd582bd4c4bbfadd1f278465b3359" IsByBinding="true" BindLocalVarGUID="BsVar_2343c277720c42189d5a8ca3bf09400e"/>
				<BaseVariable VariableName="IsExcuteSuccessful" InOutType="1" Value="" IsOptional="true" VariableType="bool" BaseDataType="bool" DefaultValue="" GUID="BsVar_8494182f87d74196b6610faf3bd8289c" BindLocalVarGUID=""/>
				<BaseVariable VariableName="VciResult" InOutType="1" Value="VciResult" IsOptional="true" VariableType="vciResult" BaseDataType="string" DefaultValue="" GUID="BsVar_3177e69ab6d74304b66640859578099a" IsByBinding="true" BindLocalVarGUID="BsVar_1123c277720c42189d5a8ca3bf09400e"/>
			</BaseVariables>
			<Assement IsActive="true" Action="Repeat" IsAssmentAtOKEnable="true" IsAssmentAtNOKEnable="false" IsAssmentAtAbortEnable="false" IsAssmentAtProgramaticEnable="true" ProgramaticAssement="1111"/>
		</Step>
		<Step StepType="106" StepName="CheckFactoryMode" Title="CheckFactoryMode" GUID="Stp_9080ff07c28845d2bff755dbd58689b4" isActive="true">
			<Conditions>
				<Condition Type="LAS" xsi:type="LASCondition" IsActive="true">
					<LASRef LasId="BsVar_1123c277220c42189d5a8ca3bf09400e"/>
				</Condition>
				<Condition Type="Programtic" xsi:type="ProgramticCondition" IsActive="false" ExcuteAt="Always">
					<Expression Value="true"/>
				</Condition>
				<Condition Type="PreviousResult" PreviousResult="NONE" ExcuteAt="Always" xsi:type="PreviousResultCondition" IsActive="false"/>
			</Conditions>
			<BaseVariables>
				<BaseVariable VariableName="ECU" InOutType="0" Value="SRS_DtObj" VariableType="ecuDtObj" BaseDataType="object" DefaultValue="" GUID="BsVar_6a439512b8ac4628808f4edb1482b7d0" IsByBinding="true" IsOptional="false" BindLocalVarGUID="BsVar_11320477220c42189d5a8ca3bf09400e"/>
				<BaseVariable VariableName="TargetValue" InOutType="0" Value="00000000" VariableType="string" BaseDataType="string" DefaultValue="" GUID="BsVar_0d90358315824a41b49e57347ead7883" BindLocalVarGUID=""/>
				<BaseVariable VariableName="StatStepRead" InOutType="0" Value="StatStep_FactoryModeRead" VariableType="StatStep" BaseDataType="object" DefaultValue="" GUID="BsVar_668083085cb045e293dbfdf3536dd5a3" IsByBinding="true" BindLocalVarGUID="BsVar_2356c275720c42189d5a8ca3bf09400e"/>
